---
- name: Print OS Name 
  hosts: all
    #  gather_facts: false
  tasks:
  - name: Print OS Name tasks
    debug:
      var: ansible_distribution
  - name: Print selinux mode
    debug:
      var: ansible_selinux.mode
  - name: Print RAM memory
    debug:
      var: ansible_memory_mb.real.free
  - name: Print Processor name
    debug:
      var: ansible_processor[2]
