---
- name: Add the user
  hosts: all
  remote_user: root
  become: true
    #  vars:
    #    NAME: kimjh
    #    COMM: this is test
  tasks:
  - name: Add the user22
    ansible.builtin.user:
      name: "{{NAME}}"
      comment: "{{COMM}}"
    register: usrout
  - name: print usrout name
    debug:
      var: usrout.name
  - name: print usrout comment
    debug:
      var: usrout.comment

