---
- name: DB task
  hosts: dbservers
  remote_user: root
  become: true

  tasks:
  - name: install db
    ansible.builtin.yum:
      name: mariadb-server
      state: latest

  - name: Ensure that postgresql is started
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes

  - name: install PyMySQL
    yum:
      name: python3-PyMySQL
      state: latest

  - name: Create a new database with name 'accounts'
    mysql_db:
      name: accounts
      state: present

  - name: Create database user with name 'vprofile'
    mysql_user:
      name: vprofile
      password: 'test1234'
      priv: '*.*:ALL'
      state: present
